[phases.setup]
# Node + npm garantidos
nixPkgs = ["nodejs"]

[phases.install]
# Instala no ROOT para linkar workspaces (inclui @deco/sdk local) e mapeia o JSR
cmds = [
  "node -v && npm -v",
  "npm config set @jsr:registry https://npm.jsr.io",
  "npm install --workspaces --include-workspace-root --no-fund --no-audit --legacy-peer-deps"
]

[phases.build]
# Builda apenas o frontend (assets para o Wrangler)
cmds = [
  "npm run -w apps/web build"
]

[start]
# Sobe o Worker da API e serve assets do dist
cmd = "npx wrangler dev --config=./wrangler.toml --local --ip 0.0.0.0 --port $PORT"
