[phases.setup]
# Instala Node 20 (com npm) e Deno (opcional; não quebra)
nixPkgs = ["nodejs_20", "deno"]

[phases.install]
# Garante que npm/node estão disponíveis e instala dependências das subpastas
cmds = [
  "node -v && npm -v",
  "npm --prefix apps/api ci --legacy-peer-deps || npm --prefix apps/api install --legacy-peer-deps",
  "npm --prefix apps/web ci --legacy-peer-deps || npm --prefix apps/web install --legacy-peer-deps"
]

[phases.build]
# Build do frontend (gera apps/web/dist)
cmds = [
  "npm --prefix apps/web run build"
]

[start]
# Sobe o Worker (API) e serve os assets do build
cmd = "npx wrangler dev --config=./wrangler.toml --local --ip 0.0.0.0 --port $PORT"
