[phases.setup]
# Node + npm garantidos; Deno opcional
nixPkgs = ["nodejs", "deno"]

[phases.install]
# Só instala o frontend; NÃO toca apps/api (que tem JSR direto)
cmds = [
  "node -v && npm -v",
  "npm --prefix apps/web install --no-fund --no-audit --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm --prefix apps/web run build"
]

[start]
cmd = "npx wrangler dev --config=./wrangler.toml --local --ip 0.0.0.0 --port $PORT"
