[phases.setup]
# Node + npm garantidos; Deno opcional
nixPkgs = ["nodejs", "deno"]

[phases.install]
# 1) Mostra versões
# 2) Força o npm a conhecer o registry JSR (independe de .npmrc)
# 3) Instala o WEB dentro do diretório correto (sem usar --prefix)
cmds = [
  "node -v && npm -v",
  "npm config set @jsr:registry https://npm.jsr.io",
  "bash -lc 'cd apps/web && npm install --no-fund --no-audit --legacy-peer-deps'"
]

[phases.build]
# Builda o frontend
cmds = [
  "bash -lc 'cd apps/web && npm run build'"
]

[start]
# Sobe a API (Worker) e serve os assets do dist
cmd = "npx wrangler dev --config=./wrangler.toml --local --ip 0.0.0.0 --port $PORT"
